config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'lists#index'
  resources :lists do
    resources :bookmarks, only: %I[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list


  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show update destroy]
  before_action :set_list, only: %i[show new create]

  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @bookmark.update(bookmark_params)
    redirect_to bookmark_path(@bookmark)
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: %i[show edit destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(strong_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @movies = Movie.all
  end

  def update
    @list.update(strong_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def strong_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container text-center">
<div class="card text-center">
<h1>New bookmark</h1>
</div>
<div class="card text-center">

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>

<% end %>

</div>

<div class="card text-center">


</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<header class="container text-center border">
  <h1>Add Movies</h1>
</header>

<div class="card text-center">
  <h2><%= @list.name %></h2>
</div>

<div class="card text-center">
  <div class="container text-center">
    <h2>Movies</h2>

<button><%= link_to "add movies to list", new_list_bookmark_path(@list) %></button>


<div class="row row-cols-1 row-cols-md-3">
     <% @movies.each do |movie| %>
      <div class="col-md-4">
        <div class="card h-100">
                <img class="card-img-top" src="<%= movie.poster_url%>" alt="Card image cap">
          <div class="card-body">
                <h5 class="card-title"><%= movie.title %></h5>
                <p class="card-text"><%= movie.overview%></p>
          </div>
        </div>
      </div>
  <% end %>
</div>






<div class="card text-center">
<button><%= link_to "Back to lists", lists_path %></button>
</div>


<%# <button><%= link_to {:action => :create}, :method => :post %></button> %>

app/views/lists/index.html.erb
  <div class="container">

  <header> <h1>Show lists</h1></header>
  <div class="card text-center">
    <h2><%= @lists.name %></h2>


<div class="card-trip">
<% @lists.each do |list| %>
    <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to list.name, list_path(list)%></h2>
      <% end %>
    </div>
</div>
</div>




<div class="card text-center">
<button><%= link_to "Add List", new_list_path(@list) %></button>
</div>

</div>





</div>

app/views/lists/new.html.erb
<div class="container text-center">
<div class="card text-center">
<h1>New List</h1>
</div>
<div class="card text-center">

<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>


</div>

<div class="card text-center">

<button><%= link_to "Back to list", lists_path %></button>
</div>
</div>

app/views/lists/show.html.erb
<div class="container text-center border">
  <h1>Show list</h1>
<div class="card text-center">
  <h2><%= @list.name %></h2>


<div class="row row-cols-1 row-cols-md-3">
     <% @list.bookmarks.each do |bookmark| %>
      <div class="col-md-4">
        <div class="card h-100">
                <img class="card-img-top" src="<%= bookmark.movie.poster_url%>" alt="Card image cap">
          <div class="card-body">
                <h5 class="card-title"><%= bookmark.movie.title %></h5>
                <p class="card-text"><%= bookmark.comment%></p>
             <button><%= link_to "Delete", bookmark_path(bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
              %></button>
          </div>
        </div>
      </div>
  <% end %>
</div>
</div>
  <div class="card text-center">

    <button><%= link_to "Delete Entire List", list_path,
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %></button>

    <button><%= link_to "Add new movies to List", edit_list_path %></button>
  </div>
    <div class="card text-center">
      <button><%= link_to "Back to lists", lists_path %></button>
    </div>
</div>

app/views/movies/index.html.erb
<div class="container text-center">
<h1>Movies</h1>

<div class="card text-center">
<ol class="list-group">
  <% @movies.each do |list| %>
    <li class="list-group-item"><%= link_to list.title, list_path(list)%></li>

  <% end %>
  </div>